# Faça um programa que leia um valor inteiro e mostre na tela a sua tabuada.

print("****************************")
N = int(input('Digite um valor: '))
print("Tabuada de soma :")
print(" {} + 1 = {}".format(N, N+1))
print(" {} + 2 = {}".format(N, N+2))
print(" {} + 3 = {}".format(N, N+3))
print(" {} + 4 = {}".format(N, N+4))
print(" {} + 5 = {}".format(N, N+5))
print("Tabuada de subtração :")
print(" {} - 1 = {}".format(N, N-1))
print(" {} - 2 = {}".format(N, N-2))
print(" {} - 3 = {}".format(N, N-3))
print(" {} - 4 = {}".format(N, N-4))
print(" {} - 5 = {}".format(N, N-5))
print("Tabuada de multiplicação :")
print(" {} * 1 = {}".format(N, N*1))
print(" {} * 2 = {}".format(N, N*2))
print(" {} * 3 = {}".format(N, N*3))
print(" {} * 4 = {}".format(N, N*4))
print(" {} * 5 = {}".format(N, N*5))
print("Tabuada de divisão :")
print(" {} / 1 = {}".format(N, N/1))
print(" {} / 2 = {}".format(N, N/2))
print(" {} / 3 = {}".format(N, N/3))
print(" {} / 4 = {}".format(N, N/4))
print(" {} / 5 = {}".format(N, N/5))
print("****************************")

